#!/bin/bash
# SPDX-License-Identifier: PMPL-1.0-or-later
# must — Restoration utility for live-files control plane
case "$1" in
    restore)
        echo "Restoring Epistemic Form..."
        ln -sfn ../ssg/estate-ssg ../formdb/modules/ssg
        echo "✅ Links restored." ;;
    *) echo "Usage: must restore" ;;
esac
